server:
  port: 8815

spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Roshan-Patro/Config-Hotel-Management-System
          clone-on-start: true