#Server's the port number (Customized)
server:
  port: 8812
  
spring:
  application:
    name: HOTEL-SERVICE
    
#Database related properties
  datasource:
    url: jdbc:mysql://${BD_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:hotelmanagement}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Patro@1997}
    
#ORM s/w specific properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import:
    - optional:configserver:http://localhost:8815

#eureka.instance.prefer-ip-address=true
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-03494354.okta.com/oauth2/default
    audience: api://default